name: Continuous Deployment

on:
  workflow_dispatch:
  # push:
  #   branches: main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created}}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
        if: ${{ steps.release.outputs.release_created}}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created}}
